Repository clem21chan/MNIST_Digit_Recognizer, pull requests merged in 2024-04, with the labels that each got.

#30 Added boxplot to EDA
  Notebooks/MNIST_Digit_Recognizer.ipynb
Labels: enhancement

#31 MNIST EDA and baseline modelling complete
  Notebooks/MNIST_Digit_Recognizer.ipynb
Labels: enhancement

#38 Updating torch layers
  Notebooks/MNIST_PyTorch.ipynb
Labels: enhancement

#39 Updated torch network with batch_size, still overfitting though
  Notebooks/MNIST_PyTorch.ipynb
Labels: help wanted

#42 Trying out new parameters for torch
  Notebooks/MNIST_PyTorch.ipynb
Labels: enhancement

#43 Final ANN model
  Notebooks/MNIST_PyTorch.ipynb
Labels: enhancement

#46 Ran model again after fixing bug
  Notebooks/MNIST_PyTorch.ipynb
Labels: bug

#47 Figuring out CNN architecture
  Notebooks/MNIST_CNN.ipynb
Labels: help wanted

#48 Fixed CNN Layer issue
  Notebooks/MNIST_CNN.ipynb
Labels: enhancement
