Repository clem21chan/MNIST_Digit_Recognizer, pull requests merged in 2024-05, with the labels that each got.

#49 Updated CNN markdown but still have error running full data set.
  Notebooks/MNIST_CNN.ipynb
Labels: bug

#50 Fixed the data loading bug, added more markdown
  Notebooks/MNIST_CNN.ipynb
Labels: documentation

#51 Ran CNN notebook through 10 epochs
  Notebooks/MNIST_CNN.ipynb
Labels: help wanted

#52 ran CNN got 98.8% test accuracy, ran on CUDA device
  Notebooks/MNIST_CNN.ipynb
Labels: enhancement

#54 Markdowns for pytorch notebook
  Notebooks/MNIST_PyTorch.ipynb
Labels: documentation

#56 Working CNN model with predictions
  Notebooks/MNIST_CNN.ipynb
  data/cnn_submission.csv
Labels: enhancement

#58 Calvin working branch
  Notebooks/MNIST_CNN.ipynb
  Notebooks/MNIST_Digit_Recognizer.ipynb
  Notebooks/MNIST_PyTorch.ipynb
Labels: documentation
